### ISSUE TITLE
Parachute Crash backfiring

### ISSUE THREAD

**Issue by AhmadToamah2010** [sch-lda/SCH-LUA-YIMMENU#11]
Everytime i want to crash a person with parachute crash i get crashed. Please put a delay to prevent it from crashing

**Comment by AhmadToamah2010** [comment]
Yeah but its a false

**Comment by AhmadToamah2010** [comment]
@sch-lda please reply

**Comment by ege-art** [comment]
Probably depends on your memory

**Comment by sch-lda** [comment]
> @sch-lda please reply

as the readme says

This Github Repo is experimental and only kept as a backup archive. There is no guarantee of user optimization, stability, and security.

and

Due to academic commitments, updates may only be made during holidays. 

I have many things to do in real life ,and haven't played gtao for a long time. I don't want to reply now and don't care about crash/troll functions
